
DF_COLS = ['bedrooms',
 'bathrooms',
 'area',
 'pool',
 'balcony',
 'furnished',
 'maid',
 'gym',
 'brand_new',
 'burj_view',
 'sea_view',
 'beach',
 'locations_Academic City',
 'locations_Al Awir',
 'locations_Al Badaa',
 'locations_Al Barari',
 'locations_Al Barsha',
 'locations_Al Furjan',
 'locations_Al Garhoud',
 'locations_Al Hudaiba',
 'locations_Al Jaddaf',
 'locations_Al Jafiliya',
 'locations_Al Karama',
 'locations_Al Khawaneej',
 'locations_Al Lisaili',
 'locations_Al Mamzar',
 'locations_Al Manara',
 'locations_Al Mina',
 'locations_Al Mizhar',
 'locations_Al Nahda (Dubai)',
 'locations_Al Quoz',
 'locations_Al Qusais',
 'locations_Al Rashidiya',
 'locations_Al Safa',
 'locations_Al Satwa',
 'locations_Al Sufouh',
 'locations_Al Twar',
 'locations_Al Warqaa',
 'locations_Al Warsan',
 'locations_Al Wasl',
 'locations_Arabian Ranches',
 'locations_Arabian Ranches 2',
 'locations_Arabian Ranches 3',
 'locations_Arjan',
 'locations_Barsha Heights (Tecom)',
 'locations_Bluewaters Island',
 'locations_Bur Dubai',
 'locations_Business Bay',
 'locations_City of Arabia',
 'locations_Culture Village',
 'locations_DAMAC Hills',
 'locations_DAMAC Hills 2 (Akoya by DAMAC)',
 'locations_DIFC',
 'locations_Deira',
 'locations_Discovery Gardens',
 'locations_Downtown Dubai',
 'locations_Downtown Jebel Ali',
 'locations_Dubai Festival City',
 'locations_Dubai Harbour',
 'locations_Dubai Hills Estate',
 'locations_Dubai Industrial Park',
 'locations_Dubai Internet City',
 'locations_Dubai Investment Park (DIP)',
 'locations_Dubai Marina',
 'locations_Dubai Maritime City',
 'locations_Dubai Media City',
 'locations_Dubai Production City (IMPZ)',
 'locations_Dubai Residence Complex',
 'locations_Dubai Science Park',
 'locations_Dubai Silicon Oasis',
 'locations_Dubai South',
 'locations_Dubai Sports City',
 'locations_Dubai Studio City',
 'locations_Dubai Waterfront',
 'locations_Dubai World Central',
 'locations_Dubailand',
 'locations_Emirates Hills',
 'locations_Green Community',
 'locations_International City',
 'locations_Jebel Ali',
 'locations_Jumeirah',
 'locations_Jumeirah Beach Residence (JBR)',
 'locations_Jumeirah Golf Estates',
 'locations_Jumeirah Islands',
 'locations_Jumeirah Lake Towers (JLT)',
 'locations_Jumeirah Park',
 'locations_Jumeirah Village Circle (JVC)',
 'locations_Jumeirah Village Triangle (JVT)',
 'locations_Liwan',
 'locations_Liwan 2',
 'locations_Meydan City',
 'locations_Mirdif',
 'locations_Mohammed Bin Rashid City',
 'locations_Motor City',
 'locations_Mudon',
 'locations_Muhaisnah',
 'locations_Nad Al Hamar',
 'locations_Nad Al Sheba',
 'locations_Oud Al Muteena',
 'locations_Palm Jumeirah',
 'locations_Pearl Jumeirah',
 'locations_Ras Al Khor',
 'locations_Reem',
 'locations_Remraam',
 'locations_Serena',
 'locations_Sheikh Zayed Road',
 'locations_The Gardens',
 'locations_The Greens',
 'locations_The Hills',
 'locations_The Lagoons',
 'locations_The Lakes',
 'locations_The Meadows',
 'locations_The Springs',
 'locations_The Sustainable City',
 'locations_The Views',
 'locations_The Villa',
 'locations_Town Square',
 'locations_Umm Al Sheif',
 'locations_Umm Ramool',
 'locations_Umm Suqeim',
 'locations_Wadi Al Safa 2',
 'locations_Wadi Al Shabak',
 'locations_Wasl Gate',
 'locations_World Trade Centre',
 'property_types_Apartment',
 'property_types_Hotel Apartment',
 'property_types_Penthouse',
 'property_types_Townhouse',
 'property_types_Villa']