LOCATIONS = ['Academic City',
 'Al Awir',
 'Al Badaa',
 'Al Barari',
 'Al Barsha',
 'Al Furjan',
 'Al Garhoud',
 'Al Hudaiba',
 'Al Jaddaf',
 'Al Jafiliya',
 'Al Karama',
 'Al Khawaneej',
 'Al Lisaili',
 'Al Mamzar',
 'Al Manara',
 'Al Mina',
 'Al Mizhar',
 'Al Nahda (Dubai)',
 'Al Quoz',
 'Al Qusais',
 'Al Rashidiya',
 'Al Safa',
 'Al Satwa',
 'Al Sufouh',
 'Al Twar',
 'Al Warqaa',
 'Al Warsan',
 'Al Wasl',
 'Arabian Ranches',
 'Arabian Ranches 2',
 'Arabian Ranches 3',
 'Arjan',
 'Barsha Heights (Tecom)',
 'Bluewaters Island',
 'Bukadra',
 'Bur Dubai',
 'Business Bay',
 'City of Arabia',
 'Culture Village',
 'DAMAC Hills',
 'DAMAC Hills 2 (Akoya by DAMAC)',
 'DIFC',
 'Damac Lagoons',
 'Deira',
 'Deira Island',
 'Discovery Gardens',
 'Downtown Dubai',
 'Downtown Jebel Ali',
 'Dubai Festival City',
 'Dubai Harbour',
 'Dubai Hills Estate',
 'Dubai Industrial Park',
 'Dubai Internet City',
 'Dubai Investment Park (DIP)',
 'Dubai Marina',
 'Dubai Maritime City',
 'Dubai Media City',
 'Dubai Production City (IMPZ)',
 'Dubai Residence Complex',
 'Dubai Science Park',
 'Dubai Silicon Oasis',
 'Dubai South',
 'Dubai Sports City',
 'Dubai Studio City',
 'Dubai Waterfront',
 'Dubai World Central',
 'Dubailand',
 'Emirates Hills',
 'Green Community',
 'International City',
 'Jebel Ali',
 'Jumeirah',
 'Jumeirah Beach Residence (JBR)',
 'Jumeirah Golf Estates',
 'Jumeirah Heights',
 'Jumeirah Islands',
 'Jumeirah Lake Towers (JLT)',
 'Jumeirah Park',
 'Jumeirah Village Circle (JVC)',
 'Jumeirah Village Triangle (JVT)',
 'Liwan',
 'Liwan 2',
 'Meydan City',
 'Mirdif',
 'Mohammed Bin Rashid City',
 'Motor City',
 'Mudon',
 'Muhaisnah',
 'Nad Al Hamar',
 'Nad Al Sheba',
 'Nad Shamma',
 'Oud Al Muteena',
 'Palm Jebel Ali',
 'Palm Jumeirah',
 'Pearl Jumeirah',
 'Ras Al Khor',
 'Reem',
 'Remraam',
 'Serena',
 'Sheikh Zayed Road',
 'The Gardens',
 'The Greens',
 'The Hills',
 'The Lagoons',
 'The Lakes',
 'The Meadows',
 'The Springs',
 'The Sustainable City',
 'The Views',
 'The Villa',
 'The World Islands',
 'Town Square',
 'Umm Al Sheif',
 'Umm Ramool',
 'Umm Suqeim',
 'Wadi Al Safa 2',
 'Wadi Al Shabak',
 'Wasl Gate',
 'World Trade Centre']